### DISCUSSION TITLE
Integrate the energy meter in Energy card

### DISCUSSION THREAD

**Discussion by stegaroby** [gicamm/homeassistant-comelit#24] [Ideas]
Hi, first of all thank you for your great job!
I have comelit HUB with:
-Energy meter
-Temperature & humidity
- roller shutters
- boolean outputs

I was able to integrate all in my HA,but  I have a problem getting the energy meter recognized in the energy card. HA tell me:
No statistic find, and send me a link: [https://www.home-assistant.io/more-info/statistics/](url)

Do you think you can halp me?

Thanks

**Comment by gicamm** [comment]
Hi,
The integration exports a power sensor and not an energy sensor. It was a choice.
For integrating 20046821 in the energy dashboard, you need to create the 'energy' sensor.
It's pretty simple. You can create a **template** that 'converts' W in KWh.
```
sensor:
 - name: ftv_kwh
   device_class: energy
   state_class: measurement
   unit_of_measurement: kWh
   state: >
     {{ states('sensor.comelit_power_prod_ftv')|float * 1 /1000 | round(2)}}
   attributes:
       last_reset: '1970-01-01T00:00:00+00:00'

```
Then you can add the new entity to the energy dashboard, and you'll see it in your dash.

Cheers
G
